apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 286568777533.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 286568777533.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: bab49d15
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
